#!/usr/bin/python

import json
import re
import subprocess

from ansible.module_utils.basic import *

DBUS_CMD = ["dbus-launch", "--exit-with-session", "/usr/bin/dconf"]

def _escape_single_quotes(string):
    return re.sub("'", r"'\''", string)

def _set_value(key, value):

    command = ['write', key, "'%s'" % _escape_single_quotes(value)]

    return _run_dbus_command(command)

def _get_value(key):
    command = ['read', key]

    return _run_dbus_command(command)

def _run_dbus_command(args):
    return subprocess.check_output(DBUS_CMD + args).strip()

def main():

    module = AnsibleModule(
        argument_spec = {
            'state': { 'choices': ['present'], 'default': 'present' },
            'key': { 'required': True },
            'value': { 'required': True },
        },
        supports_check_mode = True,
    )

    params = module.params
    state = module.params['state']
    key = module.params['key']
    value = module.params['value']

    old_value = _get_value(key)
    changed = old_value != value

    if changed and not module.check_mode:
        _set_value(key, value)

    print json.dumps({
        'changed': changed,
        'key': key,
        'value': value,
        'old_value': old_value,
    })

main()
