#!/usr/bin/python

import json
import re
import subprocess
import os

from ansible.module_utils.basic import *

DBUS_CMD = ["dbus-launch", "/usr/bin/dconf"]

def _set_value(key, value):

    command = ['write', key, "%s" % value]

    return _run_dbus_command(command)

def _get_value(key):
    command = ['read', key]

    return _run_dbus_command(command)

def _run_dbus_command(args):
    my_env = os.environ.copy()
    my_env.pop("DBUS_SESSION_BUS_ADDRESS", None)
    return subprocess.check_output(DBUS_CMD + args, env=my_env).strip()

def main():

    module = AnsibleModule(
        argument_spec = {
            'state': { 'choices': ['present'], 'default': 'present' },
            'key': { 'required': True },
            'value': { 'required': True },
            'quote': { 'choices': ['yes','no'], 'default': 'no' }
        },
        supports_check_mode = True,
    )

    params = module.params
    state = module.params['state']
    key = module.params['key']
    value = module.params['value']
    quote = module.params['quote']
    if quote == 'yes':
        value = "'%s'" % value

    old_value = _get_value(key)
    changed = old_value != value

    if changed and not module.check_mode:
        _set_value(key, value)

    print(json.dumps({
        'changed': changed,
        'key': key,
        'value': value,
        'old_value': old_value,
    }))

main()
